# Generated by Django 2.2 on 2019-05-21 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20190510_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в корзиину')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего корзину')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_in_cart', to='books.Book', verbose_name='Товар')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='cart.Cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'unique_together': {('cart', 'book')},
            },
        ),
    ]
