# Generated by Django 2.2 on 2019-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
    ]
