# Generated by Django 2.2 on 2019-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('author_last_name', models.CharField(max_length=80, verbose_name='Фамилия автора')),
                ('author_country', models.CharField(max_length=80, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['author_last_name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('publisher_adress', models.CharField(max_length=80, verbose_name='Фамилия автора')),
                ('publisher_country', models.CharField(max_length=80, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Серия')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
        ),
    ]
