# Generated by Django 2.2 on 2019-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('author_last_name', models.CharField(max_length=80, verbose_name='Фамилия автора')),
                ('country', models.CharField(max_length=80, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(choices=[('Ф', 'Фантастика'), ('Д', 'Детективы'), ('Р', 'Рассказ'), ('Б', 'Биография'), ('У', 'Учебные материалы'), ('М', 'Манга')], max_length=1, verbose_name='Название жанра')),
                ('genre_description', models.CharField(max_length=300, verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Серия')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
        ),
    ]
