# Generated by Django 2.2 on 2019-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(default='1', max_length=100, verbose_name='Название жанра')),
                ('genre_description', models.CharField(default='1', max_length=300, verbose_name='Описание жанра')),
            ],
        ),
    ]
