# Generated by Django 2.2 on 2019-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_description',
            field=models.CharField(max_length=300, verbose_name='Описание жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_type',
            field=models.CharField(max_length=100, verbose_name='Название жанра'),
        ),
    ]
