# Generated by Django 2.2 on 2019-04-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20190406_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('publisher_adress', models.CharField(max_length=80, verbose_name='Фамилия автора')),
                ('publisher_country', models.CharField(max_length=80, verbose_name='Страна')),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='country',
            new_name='author_country',
        ),
    ]
