# Generated by Django 2.2 on 2019-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20190410_0016'),
        ('books', '0007_auto_20190410_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Но-овый жанррр!', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_country',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_last_name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_type',
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='aaaaa', max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='bbb', max_length=25, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
