# Generated by Django 2.2 on 2019-04-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190410_0025'),
        ('dictionaries', '0005_auto_20190410_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genre1',
        ),
    ]
