# Generated by Django 2.2 on 2019-04-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0007_auto_20190410_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre2',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
