# Generated by Django 2.2 on 2019-04-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190424_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='active',
        ),
    ]
