# Generated by Django 2.2 on 2019-04-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название книги')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Название книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена книги (BYN)')),
                ('issue_year', models.IntegerField(default=1913, verbose_name='Год издания')),
                ('avaliable', models.BooleanField(default=True, verbose_name='Доступно для заказа')),
                ('rate', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ManyToManyField(to='dictionaries.Author', verbose_name='Авторы')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='dictionaries.Serie', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
    ]
