# Generated by Django 2.2 on 2019-04-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_date',
        ),
    ]
