# Generated by Django 2.2 on 2019-04-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_genre'),
        ('books', '0003_auto_20190410_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default='aaa', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='dictionaries.Genre', verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
