# Generated by Django 2.2 on 2019-04-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20190410_0016'),
        ('books', '0006_auto_20190410_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.Binding', verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во книг в наличии'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.BookFormat', verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.Publish', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, гр'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='dictionaries.Author', verbose_name='Автор'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='dictionaries.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='sss', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dictionaries.Series', verbose_name='Серия'),
        ),
    ]
