# Generated by Django 2.2 on 2019-04-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190410_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genre1',
        ),
    ]
