# Generated by Django 2.2 on 2019-04-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190410_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre1',
        ),
    ]
