# Generated by Django 2.2 on 2019-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0007_auto_20190410_0028'),
        ('books', '0009_remove_book_genre1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre2',
            field=models.ManyToManyField(blank=True, related_name='books', to='dictionaries.Genre2', verbose_name='Жанр'),
        ),
    ]
