# Generated by Django 2.2 on 2019-04-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Обложка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('isbn', models.CharField(default='0', max_length=20, unique=True, verbose_name='ISBN')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, гр')),
                ('age_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения')),
                ('book_amount', models.PositiveIntegerField(default=0, verbose_name='Кол-во книг в наличии')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('rate', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('author', models.ManyToManyField(related_name='books', to='data.Author', verbose_name='Автор')),
                ('bind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Binding', verbose_name='Переплет')),
                ('book_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.BookFormat', verbose_name='Формат')),
                ('genre', models.ManyToManyField(blank=True, related_name='books', to='data.Genre', verbose_name='Жанр')),
                ('publish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Publish', verbose_name='Издательство')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='data.Series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
