# Generated by Django 2.2 on 2019-04-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='data.Series', verbose_name='Серия'),
        ),
    ]
