# Generated by Django 2.2 on 2019-04-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190424_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Binding', verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BookFormat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Publish', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='data.Series', verbose_name='Серия'),
        ),
    ]
