# Generated by Django 2.2 on 2019-06-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190605_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='data.Series', verbose_name='Серия'),
        ),
    ]
